[options]
admin_passwd = password
limit_request = 81920000
limit_time_cpu = 6000
limit_time_real = 12000000
addons_path = /mnt/enterprise-addons,/mnt/custom-addons
default_productivity_apps = True
proxy_mode = True